// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package providers

import (
	"context"
	"github.com/MigAru/poseidon/internal/ping"
	"github.com/MigAru/poseidon/internal/registry/base"
	"github.com/MigAru/poseidon/internal/registry/blob"
	"github.com/MigAru/poseidon/internal/registry/manifest"
)

// Injectors from wire.go:

func InitializeBackend(ctx context.Context) (Backend, func(), error) {
	config, err := ProvideConfigFromEnv()
	if err != nil {
		return Backend{}, nil, err
	}
	logger, cleanup, err := ProvideNewLogger(config)
	if err != nil {
		return Backend{}, nil, err
	}
	pingController := ping.NewPingController()
	fileSystem := ProvideFileSystemBlobRepository()
	repositoryFileSystem := ProvideFileSystemDigestRepository()
	controller := blob.NewController(logger, fileSystem, repositoryFileSystem)
	baseController := base.NewController(logger)
	fileSystem2 := ProvideFileSystemManifestRepository()
	manifestController := manifest.NewController(logger, fileSystem2, repositoryFileSystem)
	server := ServerProvider(config, logger, pingController, controller, baseController, manifestController)
	backend, err := BackendServiceProvider(ctx, server)
	if err != nil {
		cleanup()
		return Backend{}, nil, err
	}
	return backend, func() {
		cleanup()
	}, nil
}

// wire.go:

type Backend struct{}
