// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package providers

import (
	"context"
	"github.com/MigAru/poseidon/internal/base"
	"github.com/MigAru/poseidon/internal/blob"
	"github.com/MigAru/poseidon/internal/config"
	"github.com/MigAru/poseidon/internal/database"
	"github.com/MigAru/poseidon/internal/file_system"
	"github.com/MigAru/poseidon/internal/gin"
	"github.com/MigAru/poseidon/internal/logger"
	"github.com/MigAru/poseidon/internal/manifest"
	"github.com/MigAru/poseidon/internal/ping"
	"github.com/MigAru/poseidon/internal/tech"
	"github.com/MigAru/poseidon/internal/uploads"
	"github.com/MigAru/poseidon/pkg/registry/hasher"
)

// Injectors from wire.go:

func InitializeBackend(ctx context.Context) (Backend, func(), error) {
	configConfig, err := config.NewFromEnv()
	if err != nil {
		return Backend{}, nil, err
	}
	logrusLogger, cleanup, err := logger.NewLogrus(configConfig)
	if err != nil {
		return Backend{}, nil, err
	}
	pingController := ping.NewController()
	fs := file_system.New(configConfig)
	hasherHasher := hasher.New()
	uploadsUploads := uploads.NewUploads(fs, logrusLogger, hasherHasher)
	db, cleanup2, err := database.New(configConfig)
	if err != nil {
		cleanup()
		return Backend{}, nil, err
	}
	controller := blob.NewController(logrusLogger, fs, uploadsUploads, db)
	baseController := base.NewController(logrusLogger)
	manifestController := manifest.NewController(logrusLogger, uploadsUploads, fs, db)
	tagsController := tech.NewController(logrusLogger, db)
	server := gin.NewServer(configConfig, logrusLogger, pingController, controller, baseController, manifestController, tagsController)
	backend, cleanup3, err := ServiceProvider(ctx, server)
	if err != nil {
		cleanup2()
		cleanup()
		return Backend{}, nil, err
	}
	return backend, func() {
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}

// wire.go:

type Backend struct{}
